# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'a.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        palette=QtGui.QPalette()
        pix=QtGui.QPixmap("bg_image.png")
        pix=pix.scaled(int(MainWindow.width()),int(MainWindow.height()))
        palette.setBrush(MainWindow.backgroundRole(),QtGui.QBrush(QtGui.QPixmap(pix)))
        MainWindow.setPalette(palette)
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_A_to_D = QtWidgets.QPushButton(self.centralwidget)
        self.btn_A_to_D.setGeometry(QtCore.QRect(100, 100, 50, 30))
        self.btn_A_to_D.setObjectName("btn_A_to_D")
        self.btn_A_to_D.setStyleSheet("QPushButton{color: white}"
                                      "QPushButton{font: 8pt \"Agency FB\";\n}"
                                      "QPushButton{background-image: url(blue.png)}"
                                      "QPushButton{border:2px solid white}"
                                      "QPushButton{border-radius:10px;}")
        self.btn_A_to_B = QtWidgets.QPushButton(self.centralwidget)
        self.btn_A_to_B.setGeometry(QtCore.QRect(330, 200, 120, 60))
        self.btn_A_to_B.setObjectName("btn_A_to_B")
        self.btn_A_to_B.setStyleSheet("QPushButton{color: white}"
            "QPushButton{font: 12pt \"Agency FB\";\n}"
            "QPushButton{background-image: url(blue.png)}"
            "QPushButton{border:2px solid white}"
            "QPushButton{border-radius:20px;}")
        self.btn_A_to_C = QtWidgets.QPushButton(self.centralwidget)
        self.btn_A_to_C.setGeometry(QtCore.QRect(330, 300, 120, 60))
        self.btn_A_to_C.setObjectName("btn_A_to_C")
        self.btn_A_to_C.setStyleSheet("QPushButton{color: white}"
                                      "QPushButton{font: 12pt \"Agency FB\";\n}"
                                      "QPushButton{background-image: url(blue.png)}"
                                      "QPushButton{border:2px solid white}"
                                      "QPushButton{border-radius:20px;}")
        # self.text_A = QtWidgets.QTextEdit(self.centralwidget)
        # self.text_A.setGeometry(QtCore.QRect(320, 160, 141, 51))
        # self.text_A.setObjectName("text_A")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)



























        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "空间伴侣"))
        self.btn_A_to_B.setText(_translate("MainWindow", "文案创作"))
        self.btn_A_to_C.setText(_translate("MainWindow", "文本改错"))
        self.btn_A_to_D.setText(_translate("MainWindow", "详情"))
#         self.text_A.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
# "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
# "p, li { white-space: pre-wrap; }\n"
# "</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
# "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">这是页面A</p></body></html>"))
