# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'b.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QFont
from PyQt5.QtWidgets import QTextEdit


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        palette = QtGui.QPalette()
        pix = QtGui.QPixmap("BG.jpeg")
        pix = pix.scaled(int(MainWindow.width()), int(MainWindow.height()))
        palette.setBrush(MainWindow.backgroundRole(), QtGui.QBrush(QtGui.QPixmap(pix)))
        MainWindow.setPalette(palette)
        MainWindow.setAutoFillBackground(True)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        MainWindow.setCentralWidget(self.centralwidget)
        self.centralwidget.setObjectName("centralwidget")

        self.btn_D_to_A = QtWidgets.QPushButton(self.centralwidget)
        self.btn_D_to_A.setGeometry(QtCore.QRect(50,50, 75, 23))
        self.btn_D_to_A.setObjectName("btn_D_to_A")
        font = QFont("微软雅黑", 15)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(350, 50, 221, 61))
        self.label.setObjectName("label")
        self.label.setFont(font)
        self.label.setStyleSheet("color:white")


        self.text_D_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.text_D_1.setGeometry(QtCore.QRect(150, 130, 533,50))
        self.text_D_1.setObjectName("text_D")
        self.text_D_1.setStyleSheet("border:none;")

        self.text_D_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.text_D_2.setGeometry(QtCore.QRect(150, 180, 533, 50))
        self.text_D_2.setObjectName("text_D")
        self.text_D_2.setStyleSheet("border:none;")
        # self.text_D_2.setStyleSheet("background:transparent")


        self.text_D_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.text_D_3.setGeometry(QtCore.QRect(150, 230, 533, 50))
        self.text_D_3.setObjectName("text_D")
        self.text_D_3.setStyleSheet("border:none;")
        # self.text_D_3.setStyleSheet("background:transparent")

        self.text_D_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.text_D_4.setGeometry(QtCore.QRect(150, 280, 533, 50))
        self.text_D_4.setObjectName("text_D")
        self.text_D_4.setStyleSheet("border:none;")
        # self.text_D_4.setStyleSheet("background:transparent")
        MainWindow.setCentralWidget(self.centralwidget)

        # self.text_D_5 = QtWidgets.QLineEdit(self.centralwidget)
        # self.text_D_5.setGeometry(QtCore.QRect(150, 280, 533, 50))
        # self.text_D_5.setObjectName("text_D")
        # self.text_D_5.setStyleSheet("background:transparent")
        # MainWindow.setCentralWidget(self.centralwidget)
        #
        # self.text_D_6 = QtWidgets.QLineEdit(self.centralwidget)
        # self.text_D_6.setGeometry(QtCore.QRect(150, 280, 533, 50))
        # self.text_D_6.setObjectName("text_D")
        # self.text_D_6.setStyleSheet("background:transparent")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "空间伴侣"))
        self.btn_D_to_A.setText(_translate("MainWindow", "返回"))
        self.label.setText(_translate("MainWindow", "软件说明"))
        self.text_D_1.setText(_translate("MainWindow","空间伴侣主要面向的用户是朋友圈、动态控件以及大量网站上的文"))

        self.text_D_2.setText(_translate("MainWindow","案发布者。可以解决用户有文案主题但不知道如何发布精美文案，"))
        self.text_D_3.setText(_translate("MainWindow","此外，还可以对用户编辑好的文案进行文案纠错，不仅提高了用户"))
        self.text_D_4.setText(_translate("MainWindow","的效率，也使得用户发布的文本更加准确事宜。"))